#!/usr/bin/env python
import unittest

class Person:
	def __init__(self,n):
		self.name = n
		self.max_pets = 2
		self.pets = [None] * self.max_pets
		self.num_pets = 0
		
	def add(self, pet ):
		if (self.num_pets < self.max_pets):
			self.pets[self.num_pets] = pet
			print("Succesfuly added " + str(pet.name))
			self.num_pets += 1
		else:
			print("error, cant have more pets")
		
class Pet:
	def __init__(self, n):
		self.name = n
		
	
class TestClass(unittest.TestCase):
	
	def test_add(self):
		person = Person("Bob")
		pet = Pet("egg")
		
		self.assertTrue(person.num_pets==0)
		person.add(pet)
		self.assertTrue(person.num_pets==1)
	
	def test_add_many(self):
		person = Person("Bob")
		pet = Pet("egg")
		pet2 = Pet("miro")
		pet3 = Pet("dog")
		
		person.add(pet)
		person.add(pet2)
		person.add(pet3)
		
		self.assertTrue(person.num_pets == 2)
		
if __name__ == '__main__':
	unittest.main()
	